# Generated by Django 5.1.7 on 2025-11-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_tofficer_user_delete_game_delete_tofficer'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Special Needs', 'Special Needs')], max_length=15, null=True)),
                ('payment', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_enrollments', to='school.age')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_enrollments', to='accounts.tournament')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.school')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_enrollments', to='accounts.sport')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletes', models.ManyToManyField(to='school.athlete')),
                ('school_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_enrollments', to='enrollments.schoolenrollment')),
            ],
        ),
    ]
