# Generated by Django 5.1.7 on 2025-11-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_tofficer_user_delete_game_delete_tofficer'),
        ('enrollments', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolenrollment',
            unique_together={('school', 'championship', 'sport', 'age')},
        ),
        migrations.RemoveField(
            model_name='schoolenrollment',
            name='payment',
        ),
    ]
