# Generated by Django 5.1.7 on 2025-11-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_tofficer_user_delete_game_delete_tofficer'),
        ('enrollments', '0002_alter_schoolenrollment_unique_together_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolenrollment',
            unique_together={('school', 'championship', 'sport', 'age', 'gender')},
        ),
    ]
