# Generated by Django 4.2 on 2024-05-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0008_remove_school_city_remove_school_municipality'),
        ('accounts', '0004_tofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.age')),
                ('athletes', models.ManyToManyField(to='dashboard.athlete')),
                ('championship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tournament')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.school')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sport')),
            ],
        ),
    ]
