# Generated by Django 4.2 on 2024-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_schoolteam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
    ]
