# Generated by Django 4.2 on 2024-04-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_officer'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cito', to='accounts.district'),
        ),
    ]
