# Generated by Django 4.2 on 2024-04-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_officer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=19, null=True),
        ),
    ]
