# Generated by Django 4.2 on 2024-04-27 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_officer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_alter_school_status'),
        ('core', '0003_alter_officer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('athletes', models.ManyToManyField(to='dashboard.athlete')),
                ('team_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sport')),
            ],
        ),
    ]
