# Generated by Django 4.2 on 2024-05-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_school_status'),
        ('core', '0006_tofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.age'),
        ),
    ]
