# Generated by Django 4.2 on 2024-05-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_team_team_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='tofficer',
            name='district',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
