# Generated by Django 4.2 on 2024-05-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tofficer_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TOfficer',
        ),
    ]
