# Generated by Django 4.2 on 2024-05-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tofficer'),
        ('core', '0010_delete_tofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='championship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tournament'),
        ),
    ]
