# Generated by Django 4.2 on 2024-07-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_school_city_remove_school_municipality'),
        ('core', '0011_team_championship'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.age'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
    ]
