# Generated by Django 4.2 on 2024-07-24 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_team_team_age_alter_team_team_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
