# Generated by Django 4.2 on 2024-02-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_official',
            name='role',
            field=models.CharField(blank=True, choices=[('Head Teacher', 'Head Teacher'), ('Games Teacher', 'Games Teacher'), ('Coach', 'Coach'), ('Teacher', 'Teacher'), ('Assistant Games Teacher', 'Assistant Games Teacher'), ('Assistant Head Teacher', 'Assistant Head Teacher'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('District Education Officer', 'District Education Officer'), ('District Sports Officer', 'District Sports Officer')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('athletes', models.ManyToManyField(to='dashboard.athlete')),
            ],
        ),
    ]
