# Generated by Django 4.2 on 2024-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_school_official_role_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
