# Generated by Django 4.2 on 2024-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_athlete_is_paid_alter_athlete_parent_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='lin',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
