# Generated by Django 5.0.1 on 2024-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_school_zone_school_county_school_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='Parent_guadian',
            new_name='Parent_fname',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='parent_gender',
        ),
        migrations.AddField(
            model_name='athlete',
            name='Parent_lname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='mname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
