# Generated by Django 5.0.1 on 2024-02-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_athlete_lin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True),
        ),
    ]
