# Generated by Django 4.2 on 2024-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_athlete_lin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='mname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
