# Generated by Django 5.0.1 on 2024-02-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_municipality_remove_county_district_and_more'),
        ('dashboard', '0003_alter_athlete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='county',
        ),
        migrations.RemoveField(
            model_name='school',
            name='subcounty',
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcounty', to='accounts.city'),
        ),
        migrations.AddField(
            model_name='school',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county', to='accounts.municipality'),
        ),
    ]
