# Generated by Django 4.2 on 2024-05-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_school_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='municipality',
        ),
    ]
