# Generated by Django 5.0.1 on 2024-02-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Championship',
            new_name='Tournament',
        ),
    ]
