# Generated by Django 5.0.1 on 2024-02-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_municipality_remove_county_district_and_more'),
        ('dashboard', '0004_remove_school_county_remove_school_subcounty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='Subcounty',
        ),
    ]
