# Generated by Django 4.2 on 2024-04-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_officer',
        ),
    ]
