# Generated by Django 4.2 on 2024-05-15 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=25)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('nin', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
