# Generated by Django 4.2 on 2024-06-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_tofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('contact', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=125)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=14)),
                ('designation', models.CharField(choices=[('HeadTeacher', 'HeadTeacher'), ('Assistant HeadTeacher', 'Assistant HeadTeacher')], max_length=40)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districtt', to='accounts.district')),
            ],
        ),
    ]
