# Generated by Django 4.2 on 2024-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('HeadTeacher', 'HeadTeacher'), ('Deputy HeadTeacher', 'Deputy HeadTeacher')], max_length=40),
        ),
    ]
