# Generated by Django 4.2 on 2024-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('HeadTeacher', 'HeadTeacher'), ('Deputy HeadTeacher', 'Deputy HeadTeacher')], max_length=40),
        ),
    ]
