# Generated by Django 4.2 on 2024-08-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('HeadTeacher', 'HeadTeacher'), ('Deputy HeadTeacher', 'Deputy HeadTeacher')], max_length=40, null=True),
        ),
    ]
