# Generated by Django 4.2 on 2024-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('date_of_birth', models.DateField()),
                ('school', models.CharField(max_length=125)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=14)),
                ('category', models.CharField(choices=[('Swimming Boys', 'Swimming Boys'), ('Swimming Girls', 'Swimming Girls')], max_length=40)),
                ('classroom', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=40)),
            ],
        ),
    ]
