# Generated by Django 4.2 on 2024-03-30 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0007_alter_school_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('athletes', models.ManyToManyField(related_name='enrollments', to='dashboard.athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tournament')),
                ('schools', models.ManyToManyField(related_name='enrollments', to='dashboard.school')),
            ],
        ),
    ]
