# Generated by Django 4.2 on 2024-04-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_school_status'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='competition',
            new_name='tournament',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='schools',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dashboard.school'),
            preserve_default=False,
        ),
    ]
